const dummyListings = [
  {
    id: "1",
    name: "John Doe",
    title: "Advanced Mathematics Notes",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "1234567890",
    year: "1st yr",
  },
  {
    id: "2",
    name: "Jane Smith",
    title: "Physics PYQs",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: false,
    phone: "9876543210",
    year: "2nd yr",
  },
  {
    id: "3",
    name: "Alice Brown",
    title: "Chemistry Slides",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "1122334455",
    year: "3rd yr",
  },
  {
    id: "4",
    name: "Bob Green",
    title: "Biology Notes",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: false,
    phone: "5566778899",
    year: "4th yr",
  },
 
  {
    id: "6",
    name: "User 6",
    title: "Listing Title 6",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "9876543211",
    year: "2nd yr",
  },
  {
    id: "7",
    name: "User 7",
    title: "Listing Title 7",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "8",
    name: "User 8",
    title: "Listing Title 8",
    description: "Description for listing 8.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "9",
    name: "User 9",
    title: "Listing Title 9",
    description: "Description for listing 9.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "10",
    name: "User 10",
    title: "Listing Title 10",
    description: "Description for listing 10.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
];

export default dummyListings;
