const dummyListings = [
  {
    id: "1",
    name: "John Doe",
    title: "Advanced Mathematics Notes",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "1234567890",
    year: "1st yr",
  },
  {
    id: "2",
    name: "Jane Smith",
    title: "Physics PYQs",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: false,
    phone: "9876543210",
    year: "2nd yr",
  },
  {
    id: "3",
    name: "Alice Brown",
    title: "Chemistry Slides",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "1122334455",
    year: "3rd yr",
  },
  {
    id: "4",
    name: "Bob Green",
    title: "Biology Notes",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: false,
    phone: "5566778899",
    year: "4th yr",
  },
 
  {
    id: "6",
    name: "User 6",
    title: "Listing Title 6",
    description: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "9876543211",
    year: "2nd yr",
  },
  {
    id: "7",
    name: "User 7",
    title: "Listing Title 7",
    ddescription: "Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education. Comprehensive notes covering advanced mathematics topics. Includes calculus, algebra, and geometry for higher education.",
    tags: ["Notes", "Mathematics", "Slides", "Education", "PYQs", "Physics", "Exams"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "8",
    name: "User 8",
    title: "Listing Title 8",
    description: "Description for listing 8.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "9",
    name: "User 9",
    title: "Listing Title 9",
    description: "Description for listing 9.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "10",
    name: "User 10",
    title: "Listing Title 10",
    description: "Description for listing 10.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
  {
    id: "11",
    name: "User 11",
    title: "Listing Title 11",
    description: "Description for listing 11.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345167890",
  },
  {
    id: "12",
    name: "User 12",
    title: "Listing Title 12",
    description: "Description for listing 12.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345267890",
  },
  {
    id: "13",
    name: "User 13",
    title: "Listing Title 13",
    description: "Description for listing 13.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345367890",
  },
  {
    id: "14",
    name: "User 14",
    title: "Listing Title 14",
    description: "Description for listing 14.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345467890",
  },
  {
    id: "15",
    name: "User 15",
    title: "Listing Title 15",
    description: "Description for listing 15.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345567890",
  },
  {
    id: "16",
    name: "User 16",
    title: "Listing Title 16",
    description: "Description for listing 16.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345667890",
  },
  {
    id: "17",
    name: "User 17",
    title: "Listing Title 17",
    description: "Description for listing 17.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "18",
    name: "User 18",
    title: "Listing Title 18",
    description: "Description for listing 18.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "19",
    name: "User 19",
    title: "Listing Title 19",
    description: "Description for listing 19.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "20",
    name: "User 20",
    title: "Listing Title 20",
    description: "Description for listing 20.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
  {
    id: "21",
    name: "User 21",
    title: "Listing Title 21",
    description: "Description for listing 21.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345167890",
  },
  {
    id: "22",
    name: "User 22",
    title: "Listing Title 22",
    description: "Description for listing 22.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345267890",
  },
  {
    id: "23",
    name: "User 23",
    title: "Listing Title 23",
    description: "Description for listing 23.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345367890",
  },
  {
    id: "24",
    name: "User 24",
    title: "Listing Title 24",
    description: "Description for listing 24.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345467890",
  },
  {
    id: "25",
    name: "User 25",
    title: "Listing Title 25",
    description: "Description for listing 25.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345567890",
  },
  {
    id: "26",
    name: "User 26",
    title: "Listing Title 26",
    description: "Description for listing 26.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345667890",
  },
  {
    id: "27",
    name: "User 27",
    title: "Listing Title 27",
    description: "Description for listing 27.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "28",
    name: "User 28",
    title: "Listing Title 28",
    description: "Description for listing 28.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "29",
    name: "User 29",
    title: "Listing Title 29",
    description: "Description for listing 29.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "30",
    name: "User 30",
    title: "Listing Title 30",
    description: "Description for listing 30.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
  {
    id: "31",
    name: "User 31",
    title: "Listing Title 31",
    description: "Description for listing 31.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345167890",
  },
  {
    id: "32",
    name: "User 32",
    title: "Listing Title 32",
    description: "Description for listing 32.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345267890",
  },
  {
    id: "33",
    name: "User 33",
    title: "Listing Title 33",
    description: "Description for listing 33.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345367890",
  },
  {
    id: "34",
    name: "User 34",
    title: "Listing Title 34",
    description: "Description for listing 34.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345467890",
  },
  {
    id: "35",
    name: "User 35",
    title: "Listing Title 35",
    description: "Description for listing 35.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345567890",
  },
  {
    id: "36",
    name: "User 36",
    title: "Listing Title 36",
    description: "Description for listing 36.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345667890",
  },
  {
    id: "37",
    name: "User 37",
    title: "Listing Title 37",
    description: "Description for listing 37.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "38",
    name: "User 38",
    title: "Listing Title 38",
    description: "Description for listing 38.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "39",
    name: "User 39",
    title: "Listing Title 39",
    description: "Description for listing 39.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "40",
    name: "User 40",
    title: "Listing Title 40",
    description: "Description for listing 40.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
  {
    id: "41",
    name: "User 41",
    title: "Listing Title 41",
    description: "Description for listing 41.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345167890",
  },
  {
    id: "42",
    name: "User 42",
    title: "Listing Title 42",
    description: "Description for listing 42.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345267890",
  },
  {
    id: "43",
    name: "User 43",
    title: "Listing Title 43",
    description: "Description for listing 43.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345367890",
  },
  {
    id: "44",
    name: "User 44",
    title: "Listing Title 44",
    description: "Description for listing 44.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345467890",
  },
  {
    id: "45",
    name: "User 45",
    title: "Listing Title 45",
    description: "Description for listing 45.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345567890",
  },
  {
    id: "46",
    name: "User 46",
    title: "Listing Title 46",
    description: "Description for listing 46.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345667890",
  },
  {
    id: "47",
    name: "User 47",
    title: "Listing Title 47",
    description: "Description for listing 47.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345767890",
  },
  {
    id: "48",
    name: "User 48",
    title: "Listing Title 48",
    description: "Description for listing 48.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345867890",
  },
  {
    id: "49",
    name: "User 49",
    title: "Listing Title 49",
    description: "Description for listing 49.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: true,
    phone: "12345967890",
  },
  {
    id: "50",
    name: "User 50",
    title: "Listing Title 50",
    description: "Description for listing 50.",
    tags: ["Tag1", "Tag2", "Tag3"],
    negotiable: false,
    phone: "12345067890",
  },
];

export default dummyListings;
